import { type Page } from "@playwright/test";
import { LoginPage } from '@pages/LoginPage';
import { MarketplaceLandingPage } from '@pages/MarketplaceLandingPage';
import { ProjectDetailsPage } from '@pages/ProjectDetailsPage';
import { ProjectUnitsPage } from '@pages/ProjectUnitsPage';
import { UnitDetailsPage } from '@pages/UnitDetailsPage';
import { UnitBookingPage } from '@pages/UnitBookingPage';
import { PaymentGatewayPage } from '@pages/PaymentGatewayPage';
import { BookingPage } from '@pages/BookingPage';
import { AdminProjectPage } from '@pages/AdminProjectPage';
import { DeveloperProjectPage } from '@pages/DeveloperProjectPage';
import { PaymentConfirmationPage } from '@pages/PaymentConfirmationPage';
import { AuctionPage } from '@pages/AuctionPage';
import { ElectronicAuctionProjectPage } from '@pages/ElectronicAuctionProjectPage';
import { CreateMegaProjectPage } from '@pages/CreateMegaProjectPage';
import { FlexiblePaymentPage } from '@pages/FlexiblePaymentPage';
import { BookingAndSelectPaymentMethodPage } from '@pages/BookingAndSelectPaymentMethodPage';
import { PaymentTrackingPage } from '@pages/PaymentTrackingPage';
import { RentalBehaviorPage } from '@pages/RentalBehaviorPage';
import { ResaleOfUnitsPage } from '@pages/ResaleOfUnitsPage';
import {OffPlanBasketMultipleBookingPage} from "@pages/OffPlanBasketMultipleBooking";
import { AdminLoyaltyPage } from '@pages/AdminLoyaltyPage'
import { PaymentsAndTransactionsPage } from '@pages/PaymentsAndTransactionsPage';
import { BuyDesignPage } from '@pages/BuyDesignPage';
import { WaitingListPage } from '@pages/WaitinListPage';
import { DiscountOnReservedUnitsPage } from '@pages/DiscountOnReservedUnitsPage';
import { CashPaymentPage } from '@pages/CashPaymentPage';
import { PublishUnitPage } from '@pages/PublishUnitPage';
import {UnitsDeliveryPage} from "@pages/UnitsDeliveryPage";
import { UnitComparisonPage } from '@pages/UnitComparisonPage';
import { ReportTheUnitPage } from '@pages/ReportTheUnitPage';
import { SortingPage } from '@pages/SortingPage';
import { FiltersPage } from '@pages/FiltersPage';
import { TagsPage } from '@pages/TagsPage';
import { UpdateUnitsPage } from '@pages/UpdateUnitsPage';

export class WebApp {
  page: Page;
  loginPage: InstanceType<typeof LoginPage>;
  marketplaceLandingPage: InstanceType<typeof MarketplaceLandingPage>;
  projectDetailsPage: InstanceType<typeof ProjectDetailsPage>;
  projectUnitsPage: InstanceType<typeof ProjectUnitsPage>;
  unitDetailsPage: InstanceType<typeof UnitDetailsPage>;
  unitBookingPage: InstanceType<typeof UnitBookingPage>;
  paymentGatewayPage: InstanceType<typeof PaymentGatewayPage>;
  paymentConfirmationPage: InstanceType<typeof PaymentConfirmationPage>;
  bookingPage: InstanceType<typeof BookingPage>;
  developerProjectPage: InstanceType<typeof DeveloperProjectPage>;
  auctionPage: InstanceType<typeof AuctionPage>;
  electronicAuctionProjectPage: InstanceType<typeof ElectronicAuctionProjectPage>;
  adminProjectPage: InstanceType<typeof AdminProjectPage>;
  createMegaProjectPage: InstanceType<typeof CreateMegaProjectPage>;
  flexiblePaymentPage: InstanceType<typeof FlexiblePaymentPage>;
  bookingAndSelectPaymentMethodPage: InstanceType<typeof BookingAndSelectPaymentMethodPage>;
  paymentTrackingPage: InstanceType<typeof PaymentTrackingPage>;
  rentalBehavrioPage: InstanceType<typeof RentalBehaviorPage>;
  resaleOfUnitsPage: InstanceType<typeof ResaleOfUnitsPage>;
  offPlanBasketMultipleBookingPage: InstanceType<typeof OffPlanBasketMultipleBookingPage>;
  adminLoyaltyPage: InstanceType<typeof AdminLoyaltyPage>;
  paymentsAndTransactionsPage: InstanceType<typeof PaymentsAndTransactionsPage>;
  buyDesignPage: InstanceType<typeof BuyDesignPage>;
  waitingListPage: InstanceType<typeof WaitingListPage>;
  discountOnReservedUnitsPage: InstanceType<typeof DiscountOnReservedUnitsPage>;
  cashPaymentPage: InstanceType<typeof CashPaymentPage>;
  publishUnitPage: InstanceType<typeof PublishUnitPage>;
  unitsDeliveryPage: InstanceType<typeof UnitsDeliveryPage>;

  unitComparisonPage: InstanceType<typeof UnitComparisonPage>;
  reportTheUnitPage: InstanceType<typeof ReportTheUnitPage>;
  sortingPage: InstanceType<typeof SortingPage>;
  filtersPage: InstanceType<typeof FiltersPage>;
  tagsPage: InstanceType<typeof TagsPage>;
  updateUnitsPage: InstanceType<typeof UpdateUnitsPage>;
  updateUnitsPage: InstanceType<typeof UpdateUnitsPage>;

  constructor(page: Page) {
    this.page = page;
    this.loginPage = new LoginPage(page);
    this.marketplaceLandingPage = new MarketplaceLandingPage(page);
    this.projectDetailsPage = new ProjectDetailsPage(page);
    this.projectUnitsPage = new ProjectUnitsPage(page);
    this.unitDetailsPage = new UnitDetailsPage(page);
    this.unitBookingPage = new UnitBookingPage(page);
    this.paymentGatewayPage = new PaymentGatewayPage(page);
    this.paymentConfirmationPage = new PaymentConfirmationPage(page);
    this.bookingPage = new BookingPage(page);
    this.developerProjectPage = new DeveloperProjectPage(page);
    this.auctionPage = new AuctionPage(page);
    this.electronicAuctionProjectPage = new ElectronicAuctionProjectPage(page);
    this.adminProjectPage = new AdminProjectPage(page);
    this.createMegaProjectPage = new CreateMegaProjectPage(page);
    this.flexiblePaymentPage = new FlexiblePaymentPage(page);
    this.bookingAndSelectPaymentMethodPage = new BookingAndSelectPaymentMethodPage(page);
    this.paymentTrackingPage = new PaymentTrackingPage(page);
    this.rentalBehavrioPage = new RentalBehaviorPage(page);
    this.resaleOfUnitsPage = new ResaleOfUnitsPage(page);
    this.offPlanBasketMultipleBookingPage = new OffPlanBasketMultipleBookingPage(page);
    this.adminLoyaltyPage = new AdminLoyaltyPage(page);
    this.paymentsAndTransactionsPage = new PaymentsAndTransactionsPage(page);
    this.buyDesignPage = new BuyDesignPage(page);
    this.waitingListPage = new WaitingListPage(page);
    this.discountOnReservedUnitsPage = new DiscountOnReservedUnitsPage(page);
    this.cashPaymentPage = new CashPaymentPage(page);
    this.publishUnitPage = new PublishUnitPage(page);
    this.unitComparisonPage = new UnitComparisonPage(page);
    this.reportTheUnitPage = new ReportTheUnitPage(page);
    this.sortingPage = new SortingPage(page);
    this.filtersPage = new FiltersPage(page);
    this.tagsPage = new TagsPage(page);
    this.updateUnitsPage = new UpdateUnitsPage(page);
    this.createMegaProjectPage = new CreateMegaProjectPage (page);
    this.flexiblePaymentPage = new FlexiblePaymentPage (page);
    this.bookingAndSelectPaymentMethodPage = new BookingAndSelectPaymentMethodPage (page);
    this.paymentTrackingPage = new PaymentTrackingPage (page);
    this.rentalBehavrioPage = new RentalBehaviorPage (page);
    this.resaleOfUnitsPage = new ResaleOfUnitsPage (page);
    this.offPlanBasketMultipleBookingPage = new OffPlanBasketMultipleBookingPage (page);
    this.buyDesignPage = new BuyDesignPage (page);
    this.waitingListPage = new WaitingListPage (page);
    this.discountOnReservedUnitsPage = new DiscountOnReservedUnitsPage (page);
    this.cashPaymentPage = new CashPaymentPage (page);
    this.publishUnitPage = new PublishUnitPage (page);
    this.unitsDeliveryPage = new UnitsDeliveryPage (page);
    this.updateUnitsPage = new UpdateUnitsPage(page);
  }
}
