export const ElectronicAuctionProjectObjects = {
  projectNameInput: { role: "textbox", name: "إسم المشروع" },
  auctionTypeCombobox: { role: "combobox", name: "نوع المزاد" },
  electronicAuctionOption: { role: "option", name: "الكترونية" },
  sectorCombobox: { role: "combobox", name: "نوع القطاع" },
  housingSectorOption: { text: "وزارة الإسكان" },
  regionCombobox: { xpath: "//ng-select[@formcontrolname='region_id']//input/ancestor::*[@role='combobox'][1]" },
  regionOption: { text: "الرياض" },
  cityInput: { xpath: "//input[@id='inputCity']" },
  cityOption: { role: "option", name: "الرياض", exact: true },
  auctionStartDateInput: { xpath: "//app-gregorian-datepicker[@formcontrolname='start_date']/descendant::input[@placeholder='DD/MM/YYYY']" },
  auctionEndDateInput: { xpath: "//app-gregorian-datepicker[@formcontrolname='end_date']/descendant::input[@placeholder='DD/MM/YYYY']" },
  auctionStartHourInput: { xpath: "//ngb-timepicker[@formcontrolname='start_time']/descendant::input[@aria-label='Hours']" },
  auctionStartMinuteInput: { xpath: "//ngb-timepicker[@formcontrolname='start_time']/descendant::input[@aria-label='Minutes']" },
  auctionEndHourInput: { xpath: "//ngb-timepicker[@formcontrolname='end_time']/descendant::input[@aria-label='Hours']" },
  auctionEndMinuteInput: { xpath: "//ngb-timepicker[@formcontrolname='end_time']/descendant::input[@aria-label='Minutes']" },
  saveButton: { role: "button", name: "حفظ" },
  projectMediaTab: { role: "tab", name: "وسائل الإعلام مشروع المزاد ( مسودة )" },
  arabicDetailsTitleInput: { role: "textbox", name: "عنوان صفحة التفاصيل (باللغة العربية)" },
  englishDetailsTitleInput: { role: "textbox", name: "عنوان صفحة التفاصيل (باللغة الإنجليزية)" },
  arabicNameInput: { role: "textbox", name: "الاسم (باللغة العربية)" },
  englishNameInput: { role: "textbox", name: "الاسم (باللغة الإنجليزية)" },
  arabicDescriptionInput: { role: "textbox", name: "الوصف (باللغة العربية)" },
  englishDescriptionInput: { role: "textbox", name: "الوصف (باللغة الإنجليزية)" },
  latitudeInput: { role: "spinbutton", name: "خط العرض" },
  longitudeInput: { role: "spinbutton", name: "خط الطول" },
  assetCountInput: { role: "spinbutton", name: "عدد الأصول" },
  mediaSavedMessage: { text: "تم حفظ بيانات الملف بنجاح" },
  projectDetailsButton: { text: "تفاصيل المشروع" },
  submitMediaButton: { role: "button", name: "تقديم طلب موافقة على نشر المحتوى المرفوع" },
  approveMediaButton: { role: "button", name: "قبول المحتوى المرئي المرفوع" },
  unitsTab: { role: "tab", name: "الوحدات", exact: true },
  unitsSubTab: { xpath: "#mat-tab-group-1-label-1" },
  newUnitImportButton: { xpath: "//span[normalize-space()='وحدة مزاد جديدة للاستيراد']" },
  unitTypeCombobox: { role: "combobox", name: "نوع الوحدة السكنية" },
  apartmentOption: { role: "option", name: "شقة" },
  unitFileInput: { xpath: "//input[@type='file']" },
  importSaveButton: { role: "button", name: " حفظ" },
  importInProgressMessage: { role: "none", name: "تحت الإجراء ...", exact: true },
  importCompletedMessage: { text: "تم إكمال الإجراء", exact: true },
  approveButton: { role: "button", name: "اعتماد" },
  confirmButton: { role: "button", name: "موافق" },
  backButton: { role: "button", name: "رجوع" },
  unitModelsTab: { role: "tab", name: "نماذج الوحدات" },
  modelCell: { role: "cell", name: "model_1" },
  visualMediaTab: { role: "tab", name: /المحتوى المرئي/ },
  unitPublishButton: { role: "button", name: "وحدة النشر" },
  approvedMediaTab: { xpath: "//div[@role='tab']/descendant::span[contains (text(), 'المحتوى المرئي')]" },
  auctionLegalTab: { role: "tab", name: "المزاد قانوني" },
  termsFileInput: { xpath: "//lib-sakani-upload-files[@formcontrolname='term_and_condition']//input[@type='file']" },
  winnerContractFileInput: { xpath: "//lib-sakani-upload-files[@formcontrolname='winner_contract']//input[@type='file']" },
  modelUpdatedMessage: { text: "AR Model was updated" },
  auctionSettingsTab: { role: "tab", name: "إعدادات المزاد" },
  editButton: { role: "button", name: "تعديل" },
  generalSettingSwitch: { xpath: "//ui-switch[@formcontrolname='apply_general_setting']" },
  updateButton: { role: "button", name: "تحديث" },
  arabicText: { text: "AR" },
  publishUnitModelToggle: { xpath: "//label[contains (text(), 'هل تم نشر التصانيف')]/preceding-sibling::button" },
  unitModelLink: { text: "model_1 - شقة" },
  projectApprovedMediaTab: { xpath: "//div[@role='tab']/descendant::span[contains (text(), 'وسائل الإعلام مشروع المزاد')]" },
  publishProjectToggle: { xpath: "//label[contains (text(), 'هل تم نشر المشروع')]/preceding-sibling::button" },
} as const;
