export const ProfileManagementObjects = {
    activities: "//span[contains(text(),'أنشطتي')]/../..",
    bookings: "//span[contains(text(),'الحجوزات')]/..",
    activeBookings: "//a[contains(text(),'نشطة')]",
    unit1Code: "//app-booking-list-by-status/div/div[1]/app-booking-card-v5/div/app-information-table-v5/div/div[3]/div/div[2]/div",
    unit2Code: "//app-booking-list-by-status/div/div[2]/app-booking-card-v5/div/app-information-table-v5/div/div[3]/div/div[2]/div",
    unit1Chckbox: "//app-booking-list-by-status/div/div[1]/app-booking-card-v5/div/div[2]/h5/div/app-checkbox/div/div/input",
    unit2CheckBox: "//app-booking-list-by-status/div/div[2]/app-booking-card-v5/div/div[2]/h5/div/app-checkbox/div/div/input",
    continueButton: "//button[contains(text(),' المتابعة')]",
    notBilledButton: "//a[contains(text(),'غير مدفوع')]",
    readyForSignButton: "//a[contains(text(),'جاهز للتوقيع')]",
    payBillsButton: "//button[contains(text(),'دفع الفواتير')]",
    successfulPaymentMessage: "//app-invoice-check-status/div/div/div/div/div[2]",
    projectCheckBox: "//app-smsc-booking-groupped-card/div/div/div[1]/div/app-checkbox/div/div/input",
    agreeOnAll: "//button[contains(text(),'الموافقة على الكل')]",
    verifyField: "#otpInput input:nth-child(1)",
    verifyButton: "//button[contains(text(),' تحقق ')]",
    successfulContractSignMessage: "//div[contains(text(),'تمت الموافقة على عقد البيع بنجاح. تفضل بزيارة تفاصيل حجوزاتي للوحدات.')]",
    allProjectsRadioButton: "app-toggle div > input",
} as const;
