import { execSync } from 'child_process';
import * as fs from 'fs';
import * as path from 'path';

// Format current timestamp: "YYYY-MM-DD HH-mm-ss"
const now = new Date();
const pad = (n: number): string => String(n).padStart(2, '0');
const timestamp = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${pad(now.getHours())}-${pad(now.getMinutes())}-${pad(now.getSeconds())}`;

// Define Project Root (two levels up from src/helpers/)
const projectRoot = path.resolve(__dirname, '../../');

const rawResultsDir = path.join(projectRoot, 'allure-results');
const tempReportDir = path.join(projectRoot, 'allure-report-temp');
const finalReportPath = path.join(projectRoot, `${timestamp}.html`);

try {
  console.log('Generating temporary Allure report files...');
  execSync(`npx allure generate "${rawResultsDir}" --clean -o "${tempReportDir}"`, { stdio: 'inherit' });

  console.log('Combining Allure assets into a single standalone HTML file...');
  execSync(`npx allure-single-html-file "${tempReportDir}"`, { stdio: 'inherit' });

  // allure-single-html-file outputs 'complete.html' inside tempReportDir
  const sourcePath = path.join(tempReportDir, 'complete.html');

  if (fs.existsSync(sourcePath)) {
    fs.renameSync(sourcePath, finalReportPath);
    console.log(`\nReport generated successfully at root: ${timestamp}.html`);
  } else {
    console.error('Error: complete.html was not generated by allure-single-html-file.');
  }
} catch (error) {
  const err = error as Error;
  console.error('Failed to generate report:', err.message);
} finally {
  console.log('Cleaning up temporary result folders...');
  fs.rmSync(rawResultsDir, { recursive: true, force: true });
  fs.rmSync(tempReportDir, { recursive: true, force: true });
}